Feat: move header to new sidebar
Tico4Chain-Coders/DAPP-Trustless-Work pull request #38
Opened 2024-12-02 19:55 UTC by evgongora

<p align="center"> <img src="https://github.com/user-attachments/assets/5b182044-dceb-41f5-acf0-da22dea7c98a" alt="CLR-S (2)"> </p>

# Pull Request | Trustless Work

## 1. Issue Link

- Closes #26 

---

## 2. Brief Description of the Issue

This PR implements a new collapsible and responsive sidebar that replaces most header elements while maintaining the logo, theme toggle, and wallet functionality in the header. The sidebar includes structured sections for company information, escrow operations, documentation, and profile.

## 3. Type of Change

Mark with an `x` all the checkboxes that apply (like `[x]`).

- [ ] 📝 Documentation (updates to README, docs, or comments)
- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 👌 Enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

---

## 4. Changes Made

1. Created new `AppSidebar` component with the following sections:

- Company Information with logo and description
- Collapsible Escrow section with all escrow-related operations
- Documentation section with external links
- Profile section showing wallet address

2. Key Components Used:

- `SidebarProvider` for state management
- `SidebarContent `for main content structure
- `SidebarFooter` for wallet information
- `SidebarGroup` for section organization
- `SidebarMenu` for navigation items
---

## 5. Evidence Before Solution

[Loom Video - Before Solution](https://www.loom.com/share/2eab9cfe09d34973858186d0a254a5d5?sid=ef978429-9245-493e-b9fb-6cd489a9c7ae)

---

## 6. Evidence After Solution

[Loom Video - After Solution](https://www.loom.com/share/b014d402273741fdbd94a895ada9a771?sid=e6498cd6-f65e-46ec-b567-bab68b69d8bf)

---

## 7. Important Notes

1. Component Structure:
Sidebar uses ShadcN UI components
Implements custom hooks for mobile detection
Uses React context for state management
2. Wallet Integration:
Sidebar displays formatted wallet address
Adapts to wallet connection state
Maintains consistent styling with header wallet display
3. Responsive Design:
Collapses to icon-only view on smaller screens
Full sidebar on desktop
Smooth transitions between states
4. Dependencies:
Requires ShadcN UI components
Integrates with existing wallet store
5. Testing Instructions:
Test sidebar collapse functionality
Verify wallet connection state handling
Check mobile responsiveness
Confirm dark/light theme compatibility

2024-12-02 20:34 UTC, JoelVR17 requested changes

2024-12-02 20:36 UTC, evgongora commented on src/components/sidebar/AppSidebar.tsx
Understood, I will start working on it!

2024-12-02 20:36 UTC, evgongora commented on src/components/sidebar/AppSidebar.tsx
> +        <Image src="/logo.png" alt="Trustless Work" width={24} height={24} />
Got it!

2024-12-03 04:12 UTC, evgongora commented
Made the changes! You can see it here:

https://www.loom.com/share/80eaf1a107ae4f6888c26bcc76a95ea8?sid=30953a97-275a-43f0-bb4a-1867ee18a9f6

2024-12-03 04:24 UTC, merged

2024-12-03 04:25 UTC, JoelVR17 commented
Merged!

Thanks for your work @evgongora!